### ISSUE TITLE
При запуске под пользователем, у которого нет прав на установку и удаление программ Cleaner зацикливается

### ISSUE THREAD

**Issue by ava57r** [vbondarevsky/OneCleaner#5]
При запуске окно не появляется.
через диспетчер задач видно что процесс создается, умирает и опять создается.

Встречались с таким?

**Comment by vbondarevsky** [comment]
При запуске выполняется проверка наличия административных прав и если их нет, то выполняется перезапуск с запросом этих прав. Видимо из-за каких-то ограниченных прав этот запрос не появляется и поэтому перезапуск зацикливается. Думаю, элевацию прав можно перенести ближе к удалению платформ
